### ISSUE TITLE
Use labels instead of tags to identify Machines

### ISSUE THREAD

**Issue by zuzzas** [gardener/machine-controller-manager-provider-gcp#7]
**What would you like to be added**:

We should use labels to generate Machine to GCE Instance mapping.

**Why is this needed**:

GCP has three types of "metadata":
* **tags** — used for the *firewall* rules.
* **labels** — used for grouping and quering labeled resources of all types.
* **metadata** — also k/v used when an Instance accesses the metadata server. To query something instance-specific.

It is not correct to use *tags* to  identify resources, we should rely on _labels_ to do this. We'll also have a much more efficient listing option: https://cloud.google.com/compute/docs/labeling-resources#api_3

**Comment by vlerenc** [comment]
Thanks @zuzzas. I had the same issue.

However, it appears (just checked a random machine) that we now do that, do we @rishabh-11 @elankath?

Is that now guaranteed that we use labels (e.g. with the technical ID such as `labels.k8s-cluster-name={shoot.status.technicalID}`), i.e. can I rely on that? Since when (approx.) is that the case/can I expect all GCP machines managed in a Gardener landscape to have labels/this label now?

**Comment by rishabh-11** [comment]
> Is that now guaranteed that we use labels (e.g. with the technical ID such as labels.k8s-cluster-name={shoot.status.technicalID}), i.e. can I rely on that?

This label is added in the machine class provider spec by https://github.com/gardener/gardener-extension-provider-gcp/pull/669. It has also reached the landscapes so any new machines created will have the label `labels.k8s-cluster-name={shoot.status.technicalID}`. But the instances existing before this change will not be affected and won't have the label

**Comment by rishabh-11** [comment]
>Since when (approx.) is that the case/can I expect all GCP machines managed in a Gardener landscape to have labels/this label now?

This will happen when all the machines existing before the change are replaced with new ones. This will depend on the cluster's hibernation schedule, any worker spec change, etc. which cause a rolling update. so I can't say for certain.

**Comment by rishabh-11** [comment]
@zuzzas, if you are using Gardener, you can specify the labels in the worker section of the shoot yaml, and they will be added to the VM created by the cloud provider. If you are using MCM standalone, you need to add it in the providerSpec of the machine class so that MCM can pick it up from there while creating the VM.

/close
